services:
  postgres-dev:
    extends:
      file: common-services.yml
      service: postgres
    container_name: socle_db_dev
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: socle_postgres
        target: /var/lib/postgresql/data

  postgres-test:
    extends:
      file: common-services.yml
      service: postgres
    container_name: socle_db_test
    ports:
      - target: 5432
        published: 5433
    volumes:
      - type: volume
        source: socle_postgres_test
        target: /var/lib/postgresql/data

volumes:
  socle_postgres:
  socle_postgres_test:
